kiegroup/jbpm-work-items

- dropbox-workitem/src/test/java/org/jbpm/process/workitem/dropbox/DropboxWorkitemHandlerTest.java
- google-calendar-workitem/src/test/java/org/jbpm/process/workitem/google/calendar/GoogleCalendarWorkitemHandlerTest.java
- google-mail-workitem/src/test/java/org/jbpm/workitem/google/mail/GoogleMailWorkitemHandlerTest.java
- google-sheets-workitem/src/test/java/org/jbpm/process/workitem/google/sheets/GoogleSheetsWorkitemHandlerTest.java
- google-tasks-workitem/src/test/java/org/jbpm/process/workitem/google/tasks/GoogleTasksWorkitemHandlerTest.java
> added missing junit Assert static import

- archive-workitem/src/test/java/org/jbpm/process/workitem/archive/ArchiveWorkitemIntegrationTest.java
- dropbox-workitem/src/test/java/org/jbpm/process/workitem/dropbox/DropboxWorkitemIntegrationTest.java
- exec-workitem/src/test/java/org/jbpm/process/workitem/exec/ExecWorkitemIntegrationTest.java
- ftp-workitem/src/test/java/org/jbpm/process/workitem/ftp/FTPUploadWorkitemIntegrationTest.java
- google-calendar-workitem/src/test/java/org/jbpm/process/workitem/google/calendar/GoogleCalendarWorkitemIntegrationTest.java
- google-drive-workitem/src/test/java/org/jbpm/workitem/google/drive/GoogleDriveWorkitemIntegrationTest.java
- google-mail-workitem/src/test/java/org/jbpm/workitem/google/mail/GoogleMailWorkitemIntegrationTest.java
- google-sheets-workitem/src/test/java/org/jbpm/process/workitem/google/sheets/GoogleSheetsWorkitemIntegrationTest.java
- google-tasks-workitem/src/test/java/org/jbpm/process/workitem/google/tasks/GoogleTasksWorkitemIntegrationTest.java
- ibm-watson-workitem/src/test/java/org/jbpm/process/workitem/ibm/watson/WatsonWorkitemIntegrationTest.java
- ifttt-workitem/src/test/java/org/jbpm/process/workitem/ifttt/IFTTTWorkitemIntegrationTest.java
- jabber-workitem/src/test/java/org/jbpm/process/workitem/jabber/JabberWorkitemIntegrationTest.java
- java-workitem/src/test/java/org/jbpm/process/workitem/integration/JavaHandlerWorkitemIntegrationTest.java
- jpa-workitem/src/test/java/org/jbpm/process/workitem/jpa/JPAWorkitemIntegrationTest.java
- parser-workitem/src/test/java/org/jbpm/process/workitem/parser/ParserWorkitemIntegrationTest.java
- pom.xml
- repository/pom.xml
- repository/src/test/java/HostedRepositoryIntegrationTest.java
- repository/src/test/resources/testconfig.properties
- rss-workitem/src/test/java/org/jbpm/process/workitem/rss/RSSWorkitemIntegrationTest.java
- transform-workitem/src/test/java/org/jbpm/process/workitem/transform/TransformerWorkitemIntegrationTest.java
adds integration test for each of the workitems in repository. depends on https://github.com/kiegroup/jbpm/pull/1101
> workitem handlers integration tests

- pom.xml
- repository/assembly/assembly.xml
- repository/pom.xml
- repository/src/main/resources/index.conf
- repository/src/main/resources/index.html
- repository/src/test/java/HostedRepositoryIntegrationTest.java
- twitter-workitem/.gitignore
- twitter-workitem/assembly/assembly.xml
- twitter-workitem/pom.xml
- twitter-workitem/src/main/java/org/jbpm/process/workitem/twitter/SendDirectMessageWorkitemHandler.java
- twitter-workitem/src/main/java/org/jbpm/process/workitem/twitter/TwitterAuth.java
- twitter-workitem/src/main/java/org/jbpm/process/workitem/twitter/UpdateStatusWorkitemHandler.java
- twitter-workitem/src/test/java/org/jbpm/process/workitem/twitter/TwitterWorkitemHandlerTest.java
- twitter-workitem/src/test/java/org/jbpm/process/workitem/twitter/TwitterWorkitemIntegrationTest.java
@mswiderski since we could not find the sources of the Twitter workitem that was in older repos, here is impl also using twitter4j.
> Twitter workitem

- dropbox-workitem/pom.xml
- github-workitem/pom.xml
- google-calendar-workitem/pom.xml
- google-drive-workitem/pom.xml
- google-mail-workitem/pom.xml
- google-sheets-workitem/pom.xml
- google-tasks-workitem/pom.xml
- ibm-watson-workitem/pom.xml
- ifttt-workitem/pom.xml
- java-workitem/pom.xml
- jira-workitem/.gitignore
- jira-workitem/assembly/assembly.xml
- jira-workitem/pom.xml
- jira-workitem/src/main/java/org/jbpm/process/workitem/jira/AddCommentOnIssueWorkitemHandler.java
- jira-workitem/src/main/java/org/jbpm/process/workitem/jira/CreateIssueWorkitemHandler.java
- jira-workitem/src/main/java/org/jbpm/process/workitem/jira/JiraAuth.java
- jira-workitem/src/main/java/org/jbpm/process/workitem/jira/JqlSearchWorkitemHandler.java
- jira-workitem/src/main/java/org/jbpm/process/workitem/jira/ResolveIssueWorkitemHandler.java
- jira-workitem/src/test/java/org/jbpm/process/workitem/jira/JiraWorkitemHandlerTest.java
- jira-workitem/src/test/java/org/jbpm/process/workitem/jira/JiraWorkitemIntegrationTest.java
- jpa-workitem/pom.xml
- pom.xml
- repository/assembly/assembly.xml
- repository/pom.xml
- repository/src/main/resources/index.conf
- repository/src/main/resources/index.html
- repository/src/test/java/HostedRepositoryIntegrationTest.java
> jira workitems

- archive-workitem/pom.xml
- ethereum-workitem/src/main/java/org/jbpm/process/workitem/ethereum/DeployContractWorkitemHandler.java
- ethereum-workitem/src/main/java/org/jbpm/process/workitem/ethereum/GetBalanceWorkitemHandler.java
- ethereum-workitem/src/main/java/org/jbpm/process/workitem/ethereum/ObserveContractEventWorkitemHandler.java
- ethereum-workitem/src/main/java/org/jbpm/process/workitem/ethereum/QueryExistingContractWorkitemHandler.java
- ethereum-workitem/src/main/java/org/jbpm/process/workitem/ethereum/SendEtherWorkitemHandler.java
- ethereum-workitem/src/main/java/org/jbpm/process/workitem/ethereum/TransactExistingContractWorkitemHandler.java
- ethereum-workitem/src/test/java/org/jbpm/process/workitem/ethereum/test/EthereumWorkitemHandlerTest.java
- exec-workitem/pom.xml
- google-mail-workitem/pom.xml
- parser-workitem/pom.xml
- rss-workitem/pom.xml
- template-resources/src/main/resources/indextemplate.st
depends on https://github.com/kiegroup/jbpm/pull/1179
update to ethereum workitems to define required parameters and validate them
improved handler documentation by add "required" field in the handlers index doc in generated repository, for example
> JBPM-5223 - Improve WorkItemHandler parameter definition

- archive-workitem/src/test/java/org/jbpm/process/workitem/archive/ArchiveWorkitemIntegrationTest.java
- template-resources/src/main/resources/jsontemplate.st
- template-resources/src/main/resources/widtemplate.st
updates the wid and json generation templates for https://github.com/kiegroup/jbpm/pull/1204
> update wid parameter and wid result type definition

- google-translate-workitem/src/main/java/org/jbpm/process/workitem/google/translate/TranslateWorkitemHandler.java
Hi @tsurdilo,
I didn't have time to review this WIH when it was opened as a PR so I went through it now, because it is very interesting. I have fixed one small I would say almost typo. And I have one question actually. Is this setter here https://github.com/kiegroup/jbpm-work-items/blob/master/google-translate-workitem/src/main/java/org/jbpm/process/workitem/google/translate/DetectLanguageWorkitemHandler.java#L90 really only for testing? How would you pass GoogleTranslateAuth to the WIH otherwise when registering it as WIH in engine? Thanks.
> Fix target language in Google Translate WIH

- pom.xml
- repository/pom.xml
- repository/src/test/java/HostedRepositoryIntegrationTest.java
fixes the hard-coded version used in repo integration test
> fix hard-coded version in test

- repository-springboot/pom.xml
- repository-springboot/src/main/java/org/jbpm/process/workitem/repositoryspringboot/advice/ControllerExceptionAdvice.java
- repository-springboot/src/main/java/org/jbpm/process/workitem/repositoryspringboot/config/RepositorySpringBootConfig.java
- repository-springboot/src/main/java/org/jbpm/process/workitem/repositoryspringboot/controller/RepositoryController.java
- repository-springboot/src/main/resources/application.properties
adds the spring boot actuator service. this adds several nice endpoints to the repo app such as:
/repository/env
/repository/health
/repository/beans
/repository/trace
/repository/dump
etc
> adds the spring boot actuator service

- ifttt-workitem/src/main/java/org/jbpm/process/workitem/ifttt/IFTTTWorkitemHandler.java
- ifttt-workitem/src/test/java/org/jbpm/process/workitem/ifttt/IFTTTWorkitemHandlerTest.java
@mswiderski small but important fix for ifttt workitem handler
> fix for ifttt workitem handler values

- exec-workitem/src/main/java/org/jbpm/process/workitem/exec/ExecWorkItemHandler.java
- exec-workitem/src/test/java/org/jbpm/process/workitem/exec/ExecWorkItemHandlerTest.java
- openweathermap-workitem/src/main/java/org/jbpm/process/workitem/owm/CurrentWeatherData.java
@mswiderski adds ability to get the result from the command execution in exec workitem. 
need this for next apps demo :)
> add result to exec workitem

- camel-workitem/src/test/java/org/jbpm/process/workitem/camel/CamelSqlTest.java
- exec-workitem/src/test/java/org/jbpm/process/workitem/exec/ExecWorkItemHandlerTest.java
- execute-sql-workitem/pom.xml
- execute-sql-workitem/src/test/java/org/jbpm/process/workitem/executesql/ExecuteSqlWorkItemHandlerTest.java
- jpa-workitem/pom.xml
- jpa-workitem/src/test/java/org/jbpm/process/workitem/jpa/JPAWorkItemHandlerTest.java
- pom.xml
depends on:
https://github.com/kiegroup/drools/pull/2130
https://github.com/kiegroup/jbpm/pull/1365
> [BAQE-439] Once more:  Narayana + DBCP integration

- repository-springboot/pom.xml
Hi Team, we currently do not have master nightly builds, due to the error bellow. Could someone have a look if this fix the problem?
[error.log](https://github.com/kiegroup/jbpm-work-items/files/3119807/error.log)
> Exclude duplicated dependency org.ow2.asm:asm

- pom.xml
https://issues.jboss.org/browse/JBPM-8800
> JBPM-8800: removed external spring.io repository

- camel-workitem/pom.xml
- repository-springboot/pom.xml
- repository-springboot/src/main/java/org/jbpm/process/workitem/repositoryspringboot/advice/ControllerExceptionAdvice.java
Depends on: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1086
> Bump Spring Boot version to 2.2.1

- karaf-itests/src/test/java/org/jbpm/process/workitem/camel/karaf/itests/AbstractKarafIntegrationTest.java
> DROOLS-4946 - Karaf integration tests fail

- repository-springboot/src/main/java/org/jbpm/process/workitem/repositoryspringboot/advice/ControllerExceptionAdvice.java
Merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1196
https://github.com/kiegroup/optaplanner/pull/701
https://github.com/kiegroup/optaweb-employee-rostering/pull/397
https://github.com/kiegroup/optaweb-vehicle-routing/pull/270
> [7.33.x] Fix import statement for downgrade to Spring 5.1.13

- camel-workitem/pom.xml
- jira-workitem/pom.xml
Parent PR: kiegroup/droolsjbpm-build-bootstrap#1347
> BXMSPROD-685: adding exclusions for enforcer ban-duplicated-classes

- pom.xml
Jira 
https://issues.redhat.com/browse/JBPM-9291
> [JBPM-9291] AMQ Stream (Kafka) Integration WIH / workflow component

- pom.xml
https://github.com/kiegroup/jbpm-work-items/network/alert/pom.xml/com.google.guava:guava/open
> GUAVA upgrade to 24.1.1-jre

- kafka-workitem/src/main/java/org/jbpm/process/workitem/kafka/KafkaWorkItemHandler.java
**JIRA**:  [JBPM-9346](https://issues.redhat.com/browse/JBPM-9346)
> [JBPM-9346] Exception when deploying WIH Kafka in wildfly/EAP

- kafka-workitem/src/main/java/org/jbpm/process/workitem/kafka/KafkaWorkItemHandler.java
- kafka-workitem/src/test/java/org/jbpm/process/workitem/kafka/KafkaWorkItemHandlerTest.java
- pom.xml
**JIRA**: [JBPM-9353](https://issues.redhat.com/browse/JBPM-9353)
> [JBPM-9353] Kafka WIH manages exceptions

- kafka-workitem/src/main/java/org/jbpm/process/workitem/kafka/KafkaWorkItemHandler.java
Jira https://issues.redhat.com/browse/JBPM-9369
Allow classLoader in constructor.
> [JBPM-9369] Allow Classloader in kafka workitem

- jbpm-workitem-itests/.gitignore
- jbpm-workitem-itests/README.md
- jbpm-workitem-itests/pom.xml
- jbpm-workitem-itests/src/main/java/org/jbpm/workitem/springboot/samples/JBPMApplication.java
- jbpm-workitem-itests/src/main/java/org/jbpm/workitem/springboot/samples/WebSecurityConfig.java
- jbpm-workitem-itests/src/main/resources/application.properties
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaBaseTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaFixture.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxySampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaSampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaSerializationTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/TestAutoConfiguration.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/entities/Box.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/events/listeners/CountDownLatchEventListener.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/events/listeners/CountDownLatchNotificationListener.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/serialization/BoxDeserializer.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/utils/KieJarBuildHelper.java
- jbpm-workitem-itests/src/test/resources/application-test.properties
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/pom.xml
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/java/com/myspace/kafka_process/Box.java
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/java/com/myspace/kafka_process/BoxSerializer.java
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/META-INF/kmodule.xml
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/META-INF/persistence.xml
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/com/myspace/kafka_process/kafka-process.bpmn
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/com/myspace/kafka_process/kafka_flow.bpmn
- jbpm-workitem-itests/src/test/resources/logback-test.xml
- jbpm-workitem-itests/src/test/resources/templates/kie-deployment-descriptor.template
- pom.xml
- repository/pom.xml
**JIRA**: [JBPM-9357](https://issues.redhat.com/browse/JBPM-9357)
Refactored integration tests to be included in this repo
**referenced Pull Requests**:  [droolsjbpm-build-bootstrap#1482](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1482)
> [7.44.x][JBPM-9357] Add springboot Kafka WIH tests

- exec-workitem/src/main/java/org/jbpm/process/workitem/exec/ExecShellScriptWorkItemHandler.java
- exec-workitem/src/test/java/org/jbpm/process/workitem/exec/ExecShellScriptWorkItemHandlerTest.java
- exec-workitem/src/test/java/org/jbpm/process/workitem/exec/ExecWorkitemIntegrationTest.java
- exec-workitem/src/test/resources/TestScript.sh
- repository/src/test/java/org/jbpm/process/workitem/repository/HostedRepositoryIntegrationTest.java
- repository/src/test/java/org/jbpm/process/workitem/repository/service/RepoServiceIntegrationTest.java
**JIRA**: _(please edit the JIRA link if it exists)_ 
[link](https://issues.redhat.com/browse/JBPM-9327)
<pre>
How to retest a PR or trigger a specific build:
* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>
> JBPM-9327 Add excute shell script workitem to workitem repository

- jbpm-workitem-itests/.gitignore
- jbpm-workitem-itests/README.md
- jbpm-workitem-itests/pom.xml
- jbpm-workitem-itests/src/main/java/org/jbpm/workitem/springboot/samples/JBPMApplication.java
- jbpm-workitem-itests/src/main/java/org/jbpm/workitem/springboot/samples/WebSecurityConfig.java
- jbpm-workitem-itests/src/main/resources/application.properties
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaBaseTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaFixture.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxySampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaSampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaSerializationTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/TestAutoConfiguration.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/entities/Box.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/events/listeners/CountDownLatchEventListener.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/events/listeners/CountDownLatchNotificationListener.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/serialization/BoxDeserializer.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/utils/KieJarBuildHelper.java
- jbpm-workitem-itests/src/test/resources/application-test.properties
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/pom.xml
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/java/com/myspace/kafka_process/Box.java
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/java/com/myspace/kafka_process/BoxSerializer.java
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/META-INF/kmodule.xml
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/META-INF/persistence.xml
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/com/myspace/kafka_process/kafka-process.bpmn
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/com/myspace/kafka_process/kafka_flow.bpmn
- jbpm-workitem-itests/src/test/resources/logback-test.xml
- jbpm-workitem-itests/src/test/resources/templates/kie-deployment-descriptor.template
- pom.xml
- repository/pom.xml
**JIRA**: [JBPM-9357](https://issues.redhat.com/browse/JBPM-9357)
Cherry picked from #157 
**referenced Pull Requests**:  
* [droolsjbpm-build-bootstrap#1487](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1487)
* https://github.com/kiegroup/kie-jenkins-scripts/pull/826
> [JBPM-9357] Add springboot Kafka WIH tests

- jbpm-workitem-itests/pom.xml
- kafka-workitem/pom.xml
Changing work item compilation scope, since Kafka dependency will be now
part of kie server
Merge with [#droolsjbpm-integration:2288](https://github.com/kiegroup/droolsjbpm-integration/pull/2288)
[JBPM-9436](https://issues.redhat.com/browse/JBPM-9436)
> [JBPM-9436] AMQ Streams (Kafka) listener functionality / consumer

- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaFixture.java
**JIRA**: [JBPM-9552](https://issues.redhat.com/browse/JBPM-9552)
> [JBPM-9552] Disable testcontainers tests on windows and rhel8

- jbpm-workitem-itests/pom.xml
Jira https://issues.redhat.com/browse/JBPM-9549
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1565
> [JBPM-9549] Upgrade SpringBoot to 2.3.4

- jbpm-workitem-itests/pom.xml
This reverts commit 33a22f34a9fd2b461a60370017c955715417ea45.
**JIRA**: _(please edit the JIRA link if it exists)_ 
[link](https://www.example.com)
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1579
https://github.com/kiegroup/droolsjbpm-integration/pull/2383
https://github.com/kiegroup/jbpm-work-items/pull/172
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>
* <b>a full …
> Revert "[JBPM-9549] Upgrade SpringBoot to 2.3.4 (#171)"

- kafka-workitem/pom.xml
- kafka-workitem/src/main/java/org/jbpm/process/workitem/kafka/KafkaWorkItemHandler.java
- kafka-workitem/src/test/java/org/jbpm/process/workitem/kafka/KafkaWorkItemHandlerTest.java
- pom.xml
- target/failsafe-reports/failsafe-summary.xml
Jira: https://issues.redhat.com/browse/JBPM-9455
> [JBPM-9585] Kafka WIH puts kie-server hanging if Kafka Broker is offline. (allow async)

- jbpm-workitem-itests/pom.xml
Jira :https://issues.redhat.com/browse/JBPM-9549
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1590
> [JBPM-9549] Upgrade SpringBoot to 2.3.4 (#171)

- kafka-workitem/src/main/java/org/jbpm/process/workitem/kafka/KafkaWorkItemHandler.java
https://issues.redhat.com/browse/JBPM-9660
> [JBPM-9660] Provide defaults for Kafka WIH and update ReferenceLink

- kafka-workitem/src/test/java/org/jbpm/process/workitem/kafka/KafkaWorkItemHandlerConstructorTest.java
**JIRA**: [JBPM-9665](https://issues.redhat.com/browse/JBPM-9665)
> [JBPM-9665] Add tests for default Kafka WIH

- jbpm-workitem-itests/pom.xml
**JIRA**: [JBPM-9731](https://issues.redhat.com/browse/JBPM-9731)
> [JBPM-9731] jbpm-workitem-itests failing with jdk11

- jbpm-workitem-itests/pom.xml
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaFixture.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxyAsyncSampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxyBase.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxySampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaSampleTest.java
- jbpm-workitem-itests/src/test/resources/application-test-async.properties
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/pom.xml
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/com/myspace/kafka_process/Straight_through_process.bpmn
- jbpm-workitem-itests/src/test/resources/kjars/kafka-process/src/main/resources/com/myspace/kafka_process/kafka_event_emitter.bpmn
- jbpm-workitem-itests/src/test/resources/templates/kie-deployment-descriptor.async_template
**JIRA**: [JBPM-9723](https://issues.redhat.com/browse/JBPM-9723)
**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1649
Switched also from Kafka testcontainer to Strimzi.
> [JBPM-9723] Add integration tests for Kafka WIH async

- jpa-workitem/src/test/resources/META-INF/persistence.xml
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9816)
Caused by https://issues.redhat.com/browse/JBPM-9778
> [JBPM-9816] JPAWorkItemHandlerTest test is failing for 7.57.0.Final in jbpm-work-items repo

- ethereum-workitem/src/test/java/org/jbpm/process/workitem/ethereum/test/contract/Greeter.java
- ethereum-workitem/src/test/java/org/jbpm/process/workitem/ethereum/test/contract/Mortal.java
Removing master
Exceptions 
- https://issues.redhat.com/browse/RHPAM-3697?focusedCommentId=16176154&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16176154
- https://issues.redhat.com/browse/RHPAM-3697?focusedCommentId=16176186&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16176186
- https://issues.redhat.com/browse/RHPAM-3697?focusedCommentId=16176197&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16176197
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9737)
> [JBPM-9737] Conscious Language initiative (jBPM)

- camel-workitem/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1768
* https://github.com/kiegroup/jbpm/pull/2016
* https://github.com/kiegroup/drools/pull/3832
* https://github.com/kiegroup/droolsjbpm-integration/pull/2602
* https://github.com/kiegroup/kie-jpmml-integration/pull/64
* https://github.com/kiegroup/optaplanner/pull/1574
* https://github.com/kiegroup/kie-soup/pull/227
* https://github.com/jboss-integration/rhba-installers/pull/92
> RHPAM-3897: switch to jboss-transaction-spi-jakarta

- camel-workitem/pom.xml
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1775
* https://github.com/kiegroup/jbpm/pull/2028
* https://github.com/kiegroup/drools/pull/3839
* https://github.com/kiegroup/droolsjbpm-integration/pull/2609
* https://github.com/kiegroup/kie-jpmml-integration/pull/67
* https://github.com/kiegroup/optaplanner/pull/1580
* https://github.com/kiegroup/kie-soup/pull/230
* https://github.com/jboss-integration/rhba-installers/pull/93
> [7.59.x] RHPAM-3897: switch to jboss-transaction-spi-jakarta

- long-running-rest-workitem/src/test/java/org/jbpm/process/longrest/RestServiceWorkitemIntegrationTest.java
- pastebin-workitem/readme.md
Backport of https://github.com/kiegroup/jbpm-work-items/pull/227
> [7.59.x][JBPM-9954] Conscious language initiative (#227)

- archive-workitem/pom.xml
- exec-workitem/pom.xml
- ftp-workitem/pom.xml
- jabber-workitem/pom.xml
- parser-workitem/pom.xml
- rss-workitem/pom.xml
**JIRA**: [JBPM-10024](https://issues.redhat.com/browse/JBPM-10024)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and …
> [JBPM-10024] Missing persistence dependency for tests

- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxyAsyncSampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxyBase.java
**JIRA**: [JBPM-10166](https://issues.redhat.com/browse/JBPM-10166)
> [JBPM-10166] Allow tests with productized Kafka version

- jbpm-workitem-itests/pom.xml
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaFixture.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxyAsyncSampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaProxyBase.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaSampleTest.java
- jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaSerializationTest.java
**JIRA**: [JBPM-10166](https://issues.redhat.com/browse/JBPM-10166)
**referenced Pull Requests**: 
* [droolsjbpm-build-bootstrap#2251](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2251)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build …
> [7.67.x-blue][JBPM-10093][10166] Kafka tests

- .github/workflows/pull_request.yml
**JIRA**:
* https://issues.redhat.com/browse/BXMSPROD-2067
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* paste the link(s) from GitHub here
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
[build-chain …
> [7.67.x][BXMSPROD-2067] Fix PR workflow concurrency group (#282)

- .github/workflows/pull_request.yml
**JIRA**:
* https://issues.redhat.com/browse/BXMSPROD-2067
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* paste the link(s) from GitHub here
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
[build-chain …
> [7.67.x-blue][BXMSPROD-2067] Fix PR workflow concurrency group (#282)

- docker-workitem/pom.xml
- ethereum-workitem/pom.xml
- pdf-workitem/pom.xml
- pom.xml
**JIRA**: 
- https://issues.redhat.com/browse/RHPAM-4734
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2324
* https://github.com/kiegroup/jbpm/pull/2315
* https://github.com/kiegroup/jbpm-work-items/pull/288
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds …
> org.bouncycastle.bcp.*-jdk15on to org.bouncycastle.bcp.*-jdk15to18
